services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_DB: snippetbox
      POSTGRES_USER: web
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./internal/models/testdata/db-init.sh:/docker-entrypoint-initdb.d/01-db-init.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U web -d snippetbox_test" ]
      interval: 10s
      timeout: 5s
      retries: 5
  test:
    image: golang:1.26.2-alpine
    profiles:
      - testing
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "go test -v ./cmd/web; go test -v ./internal/models/..."
    environment:
      - SNIPPETBOX_TEST_DSN=postgres://web:pass@db:5432/snippetbox_test?sslmode=disable
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
