name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: quinn-snippetbox
  REGION: us-east1
  SERVICE_NAME: snippetbox
  REGISTRY: us-east1-docker.pkg.dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.2'
      
      - name: Run Unit & Integration Tests
        run: |
          docker compose --profile testing run --rm test
  
  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider:
            'projects/346201383099/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account:
            'github-deployer@quinn-snippetbox.iam.gserviceaccount.com'
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Authorize Docker
        run: gcloud auth configure-docker ${{ env.REGISTRY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/web:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/web:${{ github.sha }}
          env_vars: IS_PROD=true,SNIPPETBOX_DSN=${{ secrets.SNIPPETBOX_DSN }}
          flags: --service-account=database-sa@quinn-snippetbox.iam.gserviceaccount.com